### ISSUE TITLE
Setting dialog does not load 

### ISSUE THREAD

**Issue by TheMayhem6328** [maoschanz/emoji-selector-for-gnome#101]
The settings of extension emoji-selector@maestroschan.fr had an error:
```
TypeError: alwaysShowLabel is null
```

Stack trace:
```
_loadPrefsPage@/home/mayhem6328/.local/share/gnome-shell/extensions/emoji-selector@maestroschan.fr/prefs.js:145:3
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
_init@/home/mayhem6328/.local/share/gnome-shell/extensions/emoji-selector@maestroschan.fr/prefs.js:41:8
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
buildPrefsWidget@/home/mayhem6328/.local/share/gnome-shell/extensions/emoji-selector@maestroschan.fr/prefs.js:199:15
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
`

**Comment by maoschanz** [comment]
I assume you're talking about the version 17

>`_loadPrefsPage@/home/mayhem6328/.local/share/gnome-shell/extensions/emoji-selector@maestroschan.fr/prefs.js:145:3`

the line 144:
 ![Capture d’écran de 2020-04-28 09-56-15](https://user-images.githubusercontent.com/19996113/80462177-9d636e80-8936-11ea-884a-d62f24b0f25c.png)

the content loaded in that builder:
![Capture d’écran de 2020-04-28 09-55-46](https://user-images.githubusercontent.com/19996113/80462210-a9e7c700-8936-11ea-86d1-32e98e02d9d9.png)

So it looks like the update partly failed: you have a new prefs.js but not the corresponding new prefs.ui

Because of #100 the update to the version 17 is disabled anyway, so you can reinstall the version 16 and wait a few days for the version 18, then please tell me if it fails again

**Comment by TheMayhem6328** [comment]
Okay... thanks for looking into it!
