### ISSUE TITLE
Emoji category buttons background color depends on the theme

### ISSUE THREAD

**Issue by yanike** [maoschanz/emoji-selector-for-gnome#107]
Emoji tab/section selector is too light to see. The icons aren't working for Ubuntu 20.04 Light theme anymore after update.

![imageoferror](https://user-images.githubusercontent.com/6353864/80675774-ee7c7b00-8a7a-11ea-9607-0cc5ad8fddee.jpg)

**Comment by yanike** [comment]
Yo! Why are you closing issues that aren't resolved???

**Comment by maoschanz** [comment]
the new version of the extension isn't released yet, but what closed the issue is the commit fixing it. The hash of this commit is listed as a clickable link just above. From a developer point of view, the issue is fixed, the code works fine 
![Capture d’écran de 2020-05-07 16-38-06](https://user-images.githubusercontent.com/19996113/81307605-25f1b580-9081-11ea-9ce1-06a5bc2cddfa.png)

the point of issue tracking is to help developer(s) know what to do next, and what i do next is fixing one of the many issues with skin colors and emoji genders: i'll not do an entire new release just for a line of CSS because some people use third-party themes...

**Comment by yanike** [comment]
Oh ok. Good to see a working version coming. Thank you :) I'll update my review once the new version comes out.
