### ISSUE TITLE
Text in search entry is white, on a white background.

### ISSUE THREAD

**Issue by fosspill** [maoschanz/emoji-selector-for-gnome#69]
Hi!
As seen in picture, typed text is white, which makes it kinda clunky to use
![image](https://user-images.githubusercontent.com/1491401/56739844-fae73d00-676f-11e9-8e45-b062421fac7e.png)

I presume this is due to a hardcoded colour conflicting with theme?

**Comment by fosspill** [comment]
Solved by changing to dark font in the settings.

**Comment by fosspill** [comment]
Closed the issue as I figured the darker font option would resolve it, but that seems to have just made the emojis darker.

**Comment by maoschanz** [comment]
What theme is this?

**Comment by fosspill** [comment]
While I don't remember the theme name, it's one of the preinstalled Pop!_OS ones, I'll find the exact name later :)

**Comment by maoschanz** [comment]
After some quick tests, it looks like my harcoded style doesn't apply to the search entry: it's only for the emojis (because i need to define their size and their font to avoid little blank squares). But concerning the search entry, it's just the `search-entry` class defined by the theme.

I think Pop OS uses a fork of Materia, where `search-entry` is defined as transparent while the text is hardcoded as white, so it has a stupid result when it's in a white menu. The original "Materia" doesn't do that however, here is "Materia Compact" for example 
![Capture d’écran de 2019-04-25 17-18-34](https://user-images.githubusercontent.com/19996113/56747489-60dac100-677e-11e9-9e00-ddec7556019c.png)

**Comment by fosspill** [comment]
Thank you! Is there anything I should do on my end then?

**Comment by maoschanz** [comment]
well... using a better theme? sadly it looks like the better solution
