### ISSUE TITLE
Category buttons don't show up

### ISSUE THREAD

**Issue by pigsflew** [maoschanz/emoji-selector-for-gnome#75]
I'm using the Materia-dark-compact shell theme.

![Screenshot from 2019-05-29 11-07-01](https://user-images.githubusercontent.com/868821/58581074-86d30580-8203-11e9-94cd-9bef0b33b816.png)

**Comment by pigsflew** [comment]
I'm also using Dash to Panel, as you can see :)

**Comment by maoschanz** [comment]
I can't reproduce, so i guess the useful informations are, as always, the distro and the GNOME Shell version. Since buttons are showing up but not their icons, provide the icon theme name too

**Comment by pigsflew** [comment]
i believe it is Noto Emoji, and the distro is Ubuntu 18.04 running the HWE kernel and video stack. Should I try with emojione, twemoji, or emojitwo?

**Comment by maoschanz** [comment]
I'm not asking for the font, but for the icon theme

**Comment by pigsflew** [comment]
Oh! I see what you're saying. Ubuntu-mono-dark--Let me try switching out the theme, icons, and shell theme to see which effects it.

![Screenshot from 2019-05-30 14-01-32](https://user-images.githubusercontent.com/868821/58664429-76925780-82e3-11e9-9cfc-00a09c6d83fd.png)

**Comment by pigsflew** [comment]
![Screenshot from 2019-05-30 14-13-29](https://user-images.githubusercontent.com/868821/58672406-a2b9d280-82fb-11e9-8adf-2c4b629b2df4.png)
![Screenshot from 2019-05-30 16-55-38](https://user-images.githubusercontent.com/868821/58672445-cb41cc80-82fb-11e9-8596-938af1181e34.png)
Nothing

**Comment by maoschanz** [comment]
Nothing is visible anyway with such a light theme, keep your Materia-dark-compact shell theme it's fine we've already look at this theory and concluded it was not the issue.

It looks like your issue is linked to #65, i don't have enough time to fix it right now so a temporary fix for your situation would be to not use a several cycles old version of the icon themes. For example go here https://github.com/GNOME/adwaita-icon-theme download it and extract it, then move the "scalable" directory to `/usr/share/icons/Adwaita/`, and overwrite the existing scalable icons from your version

**Comment by mrbmi513** [comment]
Replacing the `scalable` icons with the most up to date ones did not resolve this issue for me. Not a big issue for me since I search for everything, though.

Ubuntu 18.04.2 LTS / GNOME 3.28.2

**Comment by mrbmi513** [comment]
Replacing the `scalable` icons with the most up to date ones did not resolve this issue for me. Not a big issue for me since I search for everything, though.

Ubuntu 18.04.2 LTS / GNOME 3.28.2

Using Adapta-Nokto shell theme and Flat-Remix-Blue-Dark icons. Tried switching to Adwaita icons and copying the `scalable`s to my icon theme with no luck.

**Comment by maoschanz** [comment]
did you restart GNOME Shell after that ?

**Comment by mrbmi513** [comment]
Yes, I restarted GNOME shell, no change. Restarted my machine as well, no change.

**Comment by maoschanz** [comment]
try to install the version i just pushed?

**Comment by mrbmi513** [comment]
Latest version off github shows the category labels. Do you know how long it takes to reach the GNOME extensions site?

**Comment by maoschanz** [comment]
no, it doesn't depend on me
