### ISSUE TITLE
Can't paste Emoji into Hexchat, all other applications work

### ISSUE THREAD

**Issue by flotwig** [maoschanz/emoji-selector-for-gnome#88]
After updating GNOME to 3.34.1, I can no longer paste emoji into Hexchat 😢, but all other apps work. 

I tried changing the type here to `PRIMARY`, but the paste still didn't work when middle-clicking into Hexchat:

https://github.com/maoschanz/emoji-selector-for-gnome/blob/d82a50be64ae6454d9aba8b182735f1cfc7ab820/emoji-selector@maestroschan.fr/emojiButton.js#L13-L13

I also tried to use the Gtk + Gdk APIs to get Clipboard support, but couldn't get that to work. 🙄

Hexchat is installed as a binary, not a snap or flatpak.

Any ideas for where I can start looking to fix this issue?

Related: #60

**Comment by maoschanz** [comment]
can you paste anything at all in this app, or is it only about emojis?

**Comment by flotwig** [comment]
Oh yes, I suppose I should have mentioned this! Yeah, I can copy from any other app and paste into Hexchat just fine. It's specifically Emoji copied from the `emoji-selector-for-gnome` that just don't paste, and only with Hexchat, not any other apps that I've noticed. Thanks for getting back so quickly.

**Comment by maoschanz** [comment]
Are you using Xorg or Wayland?

**Comment by flotwig** [comment]
Xorg, unfortunately; Wayland behaves badly with my graphics card + dock.

I am on Pop_OS! 19.10 if that helps.

**Comment by maoschanz** [comment]
I can reproduce the issue on Debian Sid, but it's a general GNOME Shell issue (or an Hexchat issue?) 

I mean you can't paste things from your clipboard history using the "clipboard indicator" extension too, if you search something in the overview, select the text and do ctrl+c too, etc.

**Comment by flotwig** [comment]
Thank you for reproducing @maoschanz, I will ask in hexchat's repo and I'll post back here if I discover anything.

**Comment by flotwig** [comment]
@maoschanz Can you share your GNOME shell version that you repro'd on?

**Comment by maoschanz** [comment]
3.34.1

**Comment by tracker1** [comment]
If it helps, I'm able to copy/paste out of gedit into hexchat...  but not directly... also Pop_OS! 19.10 here.

**Comment by flotwig** [comment]
Here is the issue I opened on the GNOME GitLab: https://gitlab.gnome.org/GNOME/gnome-shell/issues/1919

**Comment by ronjouch** [comment]
Issue confirmed under GNOME Shell & Mutter 3.34.2 under Arch Linux. Additional data points:

1. It's not just Hexchat. Problem reproduced with my terminal emulator [Kitty](https://sw.kovidgoyal.net/kitty/) 0.15.1: if the clipboard was set by a Shell extension, it is un-pastable into Hexchat & Kitty.
2. The bug is not about *emojis* per se, it's only about the source being a Shell extension. So, like maoschanz said, other extensions manipulating the clipboard (e.g. Clipboard Indicator) are affected too. Say I put `🙂` and `foo` in Clipboard Indicator, then neither succeeds at being pasted into Hexchat / Kitty.
    - ... but if I *paste* `🙂` and `foo` set by Clipboard Indicator / Emoji Selector into a non-broken app (e.g. Sublime Text), then select the emoji / text here and Ctrl+C it, then pasting to Hexchat / Kitty works.

Any idea what's special about Kitty & Hexchat? @flotwig , you said you'd ask Hexchat folks, did you get any feedback from them? Are these apps using a deprecated API, or is the problem in GNOME?

Suggesting a more precise title for this issue and the GitLab issue: `Text placed into clipboard by Shell extensions become un-pastable into certain apps (Hexchat, Kitty)`.

**Comment by maoschanz** [comment]
Even weirder: the issue happens with Eclipse... but not eveywhere in Eclipse. Impossible to paste into the main source code editor, but it works in the "find and replace" dialog for example

**Comment by ronjouch** [comment]
Issue still present with Shell + Mutter 3.34.3

**Comment by ronjouch** [comment]
Closing as fixed by https://gitlab.gnome.org/GNOME/mutter/commit/41c6e1375b85f6e4513d8029e536d2c9494d9794 , see https://gitlab.gnome.org/GNOME/gnome-shell/issues/1919#note_701075

**Comment by ronjouch** [comment]
Oops, that wasnt my bug, so I cannot close it. @flotwig @maoschanz please close 🙂.

**Comment by aasutossh** [comment]
Not pastable on https://github.com/alacritty/alacritty too.
While `gnome-terminal` works.
`alacritty` says : `bracketed-paste-magic:zle:47: not enough arguments for -U`
